"""
utils/writer.py
Saves the final report to output/lit_review.md.
"""

import os
from datetime import datetime


OUTPUT_DIR  = "output"
OUTPUT_FILE = "lit_review.md"


def save_report(markdown: str) -> str:
    """
    Save the literature review markdown to output/lit_review.md.

    Args:
        markdown: the full markdown string from Step 6

    Returns:
        str: absolute path to the saved file
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)

    # Prepend a generation timestamp as an HTML comment (invisible in rendered MD)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    full_content = f"<!-- Generated by ResearchPilot on {timestamp} -->\n\n{markdown}"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_content)

    abs_path = os.path.abspath(output_path)
    return abs_path